- name: Install all soft for DB
  hosts: all
  become: true
  tasks:
    - name: Add an apt's signing key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present
    
    - name: Add specified repository into sources list
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        update_cache: true
    
    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
      notify: 
        - Replace MongoDB's socket
        - reload mongod

    - name: Enable MongoDB
      systemd: name=mongod enabled=yes

  handlers:
    - name: reload mongod
      systemd: name=mongod state=restarted

    - name: Replace MongoDB's socket
      shell: sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mongod.conf
      notify: reload mongod
